name: Output_test

on: push

jobs:
        Testing:
                runs-on: ubuntu-latest
                steps: 
                - uses: actions/checkout@v2
                - run: sudo apt-get install -y valgrind cppcheck
                - run: cppcheck *.cpp --enable=warning --error-exitcode=1
                - run: cppcheck *.cpp --enable=warning,style,performance --output-file=styleformance.txt
                - uses: actions/upload-artifact@v2
                  with:
                        name: styleformance
                        path: ./testing/styleformance.txt
                - run: clang++ *.cpp -Wall -Wextra
                - run: valgrind --leak-check=full --error-exitcode=1 ./a.out testing/units/advHalis.json testing/units/codos.json
                - run: ./testing/diff_script.sh 

