name: Output_test

on: push

jobs:
        Testing:
                runs-on: ubuntu-latest
                container: haliscsharp/nehez_eldonteni:latest
                steps: 
                - uses: actions/checkout@v2
                - run: make cppcheck
                - uses: actions/upload-artifact@v2
                  with:
                        name: styleformance
                        path: ./testing/styleformance.txt
                - run: make
                - run: make memcheck
                - run: make outputTests 
