name: JSONParse_tests

on: push

jobs:
        build_and_run_tests:
                runs-on: ubuntu-latest
                steps: 
                - uses: actions/checkout@v2
                - run: sudo apt install libgtest-dev
                - run: sudo apt install cmake

                - run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a
                - run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a

                - run: cd testing && cmake CMakeLists.txt && make && ./runTests

