name: JSONParse tests

on: push

jobs:
        build_and_run_test:
                runs-on: ubuntu-latest
                steps: 
                - uses: actions/checkout@v2
                
                - name: install gtest, cmake
                - run: sudo apt install libgtest-dev
                - run: sudo apt install cmake
                
                - name: symbolic links
                - run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a
                - run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
                
                - name: run tests
                - run: cd tests
                - run: cmake CMakeLists.txt
                - run: make
                - run: ./runTests

